version: "3"
services:
  
  mongo:
    image: "mongo"
  
  client:
    build: client/
    ports:
      - 3000:3000
    restart: always

  server:
    build: server/
    ports:
      - 8080:8080
    restart: always

